theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: content
  breadcrumb:
    position: after-hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-white.svg"
  posts:
    index:
      layout: grid
      show_categories: true
      truncate_description: 200
  pages:
    index:
      truncate_description: 200